https://www.kaggle.com/competitions/digit-recognizer/data?select=sample_submission.csv

In [86]:
import pandas as pd
from sklearn.neural_network import MLPClassifier

In [87]:
train_data = pd.read_csv('train.csv')

In [88]:
train_data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
train_data.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [90]:
y_train = train_data['label']
x_train = train_data.drop(['label'], axis=1)

In [91]:
y_train.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [92]:
x_train.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
x_train /= 255

In [94]:
clf = MLPClassifier(solver="sgd", alpha=1e-5, max_iter=80,
                    hidden_layer_sizes=(40,), verbose=10,
                    learning_rate_init=0.2, random_state=1)

In [95]:
clf.fit(x_train, y_train)

Iteration 1, loss = 0.32952454
Iteration 2, loss = 0.15199359
Iteration 3, loss = 0.11518642
Iteration 4, loss = 0.09998234
Iteration 5, loss = 0.08447855
Iteration 6, loss = 0.07765956
Iteration 7, loss = 0.06634555
Iteration 8, loss = 0.06011869
Iteration 9, loss = 0.05548717
Iteration 10, loss = 0.05116821
Iteration 11, loss = 0.04599848
Iteration 12, loss = 0.04255247
Iteration 13, loss = 0.04109791
Iteration 14, loss = 0.03678461
Iteration 15, loss = 0.03215463
Iteration 16, loss = 0.02977246
Iteration 17, loss = 0.03011310
Iteration 18, loss = 0.02820001
Iteration 19, loss = 0.02696509
Iteration 20, loss = 0.02161163
Iteration 21, loss = 0.02117332
Iteration 22, loss = 0.02023466
Iteration 23, loss = 0.02068793
Iteration 24, loss = 0.01839049
Iteration 25, loss = 0.01451861
Iteration 26, loss = 0.01166328
Iteration 27, loss = 0.01276907
Iteration 28, loss = 0.00976440
Iteration 29, loss = 0.00676109
Iteration 30, loss = 0.00504505
Iteration 31, loss = 0.00668450
Iteration 32, loss = 0.00559589
Iteration 33, loss = 0.00300728
Iteration 34, loss = 0.00142222
Iteration 35, loss = 0.00100816
Iteration 36, loss = 0.00072133
Iteration 37, loss = 0.00067813
Iteration 38, loss = 0.00060931
Iteration 39, loss = 0.00056361
Iteration 40, loss = 0.00054649
Iteration 41, loss = 0.00051971
Iteration 42, loss = 0.00049843
Iteration 43, loss = 0.00047998
Iteration 44, loss = 0.00046283
Iteration 45, loss = 0.00044744
Iteration 46, loss = 0.00043465
Iteration 47, loss = 0.00042142
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(40,), learning_rate_init=0.2,
              max_iter=80, random_state=1, solver='sgd', verbose=10)

In [96]:
x_test = pd.read_csv('test.csv')

In [97]:
x_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [98]:
x_test.isnull().sum()

pixel0      0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 784, dtype: int64

In [99]:
x_test /= 255

In [100]:
y_test = clf.predict(x_test)
y_test[:5]

array([2, 0, 9, 9, 3])

In [101]:
!touch submission.csv

In [102]:
with open("submission.csv", "w") as file:
    file.writelines("ImageId,Label\n")
    for i in range(0, len(y_test)):
        file.writelines(f'{i+1},{y_test[i]}\n')

Final score: 0.96832